#!/bin/bash -eu
#
# Copyright 2026 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Runs the Manager UI E2E suite's real-Shadowbox journey (QA automation
# Layer 2, see docs/manager-qa-automation-plan.md) against a Shadowbox
# container started for the occasion. Requires Docker.
#
# The container setup mirrors what install_server.sh generates on a real
# host: a self-signed TLS certificate, a random API prefix, and the state
# directory mounted into the container.

readonly CONTAINER_NAME='outline-manager-e2e-shadowbox'
readonly API_PORT=28443
readonly SB_IMAGE="${SB_IMAGE:-quay.io/outline/shadowbox:stable}"

STATE_DIR="$(mktemp -d)"
readonly STATE_DIR

cleanup() {
  docker rm -f "${CONTAINER_NAME}" &> /dev/null || true
  rm -rf "${STATE_DIR}"
}
trap cleanup EXIT

# Self-signed certificate, as generated by install_server.sh.
openssl req -x509 -nodes -days 1 -newkey rsa:2048 -subj '/CN=localhost' \
  -keyout "${STATE_DIR}/shadowbox-selfsigned.key" \
  -out "${STATE_DIR}/shadowbox-selfsigned.crt" 2> /dev/null

CERT_SHA256="$(openssl x509 -in "${STATE_DIR}/shadowbox-selfsigned.crt" \
  -noout -sha256 -fingerprint | sed 's/.*=//;s/://g')"
readonly CERT_SHA256

readonly SB_API_PREFIX='E2eTestApiPrefix'

docker rm -f "${CONTAINER_NAME}" &> /dev/null || true
docker run -d \
  --name "${CONTAINER_NAME}" \
  -p "127.0.0.1:${API_PORT}:${API_PORT}" \
  -v "${STATE_DIR}:/shadowbox-state" \
  -e 'SB_STATE_DIR=/shadowbox-state' \
  -e "SB_API_PORT=${API_PORT}" \
  -e "SB_API_PREFIX=${SB_API_PREFIX}" \
  -e 'SB_CERTIFICATE_FILE=/shadowbox-state/shadowbox-selfsigned.crt' \
  -e 'SB_PRIVATE_KEY_FILE=/shadowbox-state/shadowbox-selfsigned.key' \
  "${SB_IMAGE}" > /dev/null

readonly API_URL="https://localhost:${API_PORT}/${SB_API_PREFIX}"

echo "Waiting for the Shadowbox management API at ${API_URL}..."
for _ in $(seq 1 30); do
  if curl --silent --insecure --max-time 2 "${API_URL}/access-keys" > /dev/null; then
    break
  fi
  sleep 1
done
curl --silent --insecure --max-time 2 "${API_URL}/access-keys" > /dev/null \
  || { echo 'Shadowbox did not become ready'; docker logs "${CONTAINER_NAME}"; exit 1; }

# A real install creates the first access key (see install_server.sh's
# create_first_user); a bare container starts with none.
curl --silent --insecure --request POST "${API_URL}/access-keys" > /dev/null

SHADOWBOX_API_URL="${API_URL}" SHADOWBOX_CERT_SHA256="${CERT_SHA256}" \
  npm run action server_manager/e2e/test -- --grep 'real Shadowbox' "$@"
